pipeline {
    agent any

    stages {
       /* stage('checkout'){
            steps{
                 git branch: 'main', url: 'https://github.com/tarekadelkamal/dotNetApp.git'
            }
        }*/
        stage('build & push') {
            steps {
                dir('GameZone') {
                   withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'pass', usernameVariable: 'user')]) 
                    {
                         sh "docker login -u $user -p $pass"
                         sh "cd /var/jenkins_home/workspace/dotnetapp/Gamezone"
                         sh "docker compose build webapp"
                         sh "docker tag gamezone-webapp:latest tarek2020/dotnetapp:${env.BUILD_NUMBER}"
                         sh "docker push tarek2020/dotnetapp:${env.BUILD_NUMBER}"
                    } 
                }
            }
        }
        stage('deploy infrastructure') {
            steps {
               dir('GameZone') { 
                   sh 'kubectl apply -f k8s/secret.yaml'
                   sh 'kubectl apply -f k8s/db-deployment.yaml'
                   sh 'kubectl apply -f k8s/ingress.yaml'
               }
            }
        }
        stage('deploy webapp'){
            steps {
               dir('GameZone') { 
                   // Replace the 'latest' tag with the specific BUILD_NUMBER dynamically
                   sh "sed -i 's|tarek2020/dotnetapp:latest|tarek2020/dotnetapp:${env.BUILD_NUMBER}|g' k8s/app-deployment.yaml"
                   
                   // Apply the web app deployment
                   sh "kubectl apply -f k8s/app-deployment.yaml"
               }
            }
        }
    }
}
