apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
type: Opaque
stringData:
  db-password: {{ if .Values.secret }}{{ .Values.secret.dbPassword | quote }}{{ else }}"YourStrongPassword123!"{{ end }}
