apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
      - name: wait-for-sqlserver
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z sqlserver 1433; do echo "Waiting for SQL Server to start..."; sleep 5; done;']
      containers:
      - name: mcvdotnetapp
        image: tarek2020/dotnetapp:latest # This will be updated dynamically by Jenkins
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver,1433;Database=GameZone;User Id=sa;Password=$(DB_PASSWORD);TrustServerCertificate=True;Encrypt=False"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
